Mailing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('tracking.urls')),
    path('', include('batches.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views 

urlpatterns = [
    path('', views.home, name='index'),
    path('base/', views.base, name='base'),
    path('create/mailing/', views.create_mailing, name='create_mailing'),
    path('confirm-mailing/<str:token>/', views.confirm_mailing, name='confirm_mailing'),
    path('update/<int:pk>/', views.update_mailing, name='update_mailing'),
    path('view/<int:pk>/', views.view_mailing, name='view_mailing'),
] 

home/models.py
from django.db import models
from tinymce.models import HTMLField
import re

class Attachments(models.Model):
    file = models.FileField(upload_to='attachments/')
    mailing = models.ForeignKey('Mailing', related_name='attachments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file.name

class Mailing(models.Model):
    email = models.EmailField(max_length=254)
    batches = models.ManyToManyField('Batch')
    subject = models.CharField(max_length=100)
    tracking = models.BooleanField(default=False)
    message = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

    @property
    def get_attachments(self):
        return self.attachments.all()

    class Meta:
        verbose_name = 'Mailing'
        verbose_name_plural = 'Mailings'

class OTPMailing(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    otp = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Batch(models.Model):
    name = models.CharField(max_length=30)
    recipients = models.CharField(max_length=2000)

    def __str__(self):
        return str(self.name)
    @property
    def recipients_as_list(self):
        return [ recipient.strip() for recipient in self.recipients.split(',') ]
    
    class Meta:
        verbose_name = 'Batch'
        verbose_name_plural = 'Batches'

    def is_valid_email(self, email):
        email_regex = r'^[\w\.-]+@[\w\.-]+\.\w+$'
        return bool(re.match(email_regex, email))

    def save(self, *args, **kwargs):
        unique_recipients = list(set(
            email.strip() for email in self.recipients_as_list
            if email.strip() and self.is_valid_email(email)
        ))

        # Join the valid recipients back into a string
        self.recipients = ','.join(unique_recipients)

        # Call the superclass save method
        super().save(*args, **kwargs)

    
class MailingToken(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='mailing_token')
    token = models.CharField(max_length=100)
    sent = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.token
    
    @property
    def is_sent(self):
        return self.sent

templates/components/batch_list.html
<h5 class="card-header">Existing Batches</h5>
				{% if batches %}
				<div class="table-responsive text-nowrap p-2">
					<table class="table table-sm">
						<thead>
							<tr>
								<th>Name</th>
								<th>No. of recipients</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody class="table-border-bottom-0">
							{% for batch in batches %}
							<tr>
								<td><span>{{batch.name}}</span></td>
								<td>{{batch.recipients_as_list|length}}</td>
								<td class="d-flex justify-content-center">
										<button
										type="button"
										class="dropdown-item btn-sm p-0" 
										hx-get="{% url 'batch_update' pk=batch.id %}" 
										hx-target="#batchForm" 
										hx-swap="innerHTML"
										hx-on:htmx:after-swap="initTextarea()"
										>
											<i class="bx bx-edit-alt me-1"></i>
										</button>
										<button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteModal{{batch.id}}"> 
											<i class="bx bx-trash me-1"></i>
										</button>
								</td>
							</tr>
							<div
								class="modal fade"
								id="deleteModal{{batch.id}}"
								tabindex="-1"
								aria-labelledby="deleteModal{{batch.id}}Label"
								aria-hidden="true">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<h5
												class="modal-title"
												id="deleteModal{{batch.id}}Label">
												Deletion Confirmation
											</h5>
											<button
												type="button"
												class="btn-close"
												data-bs-dismiss="modal"
												aria-label="Close"></button>
										</div>
										<div class="modal-body">
											<p>
												Are you sure you want to delete:
												<br />
												"{{batch.name}}" with
												{{batch.recipients_as_list|length}}
												recipients?
											</p>
										</div>
										<div class="modal-footer">
											<button
												type="button"
												class="btn btn-secondary"
												data-bs-dismiss="modal">
												No
											</button>
											<form 
											hx-post="{% url 'batch_delete' pk=batch.id %}" 
											hx-trigger="submit" 
											hx-swap="innerHTML" 
											hx-target="#batchesListCard"
											hx-on::before-request="$('.modal')">
												{% csrf_token %}
												<button
													data-bs-dismiss="modal"
													type="submit"
													class="btn btn-danger">
													Yes
												</button>
											</form>
										</div>
									</div>
								</div>
							</div>
							{% endfor %}
						</tbody>
					</table>
				</div>
				{% else %}
				<div class="card-body">
					<p class="text-center">No batches found.</p>
				</div>
				{% endif %}

templates/components/batch_update.html
<form hx-post ={% url "batch_update" batch.id %} id="form2"
          hx-trigger="submit" 
          hx-target=".container-xxl" 
          hx-swap="afterbegin"
          hx-on:htmx:after-request="$('#form2')[0].reset()"
          hx-indicator="#loading-indicator"
          method="post">
          <div class="spinner-border" id="loading-indicator" >
          </div>
            {% csrf_token %}
            <div class="mb-4">
              <label for="id_name" class="form-label">
                Name of the Batch
              </label>
              <input
                type="text"
                class="form-control"
                id="id_name"
                name="name"
                placeholder="2078-Batch"
                required
                value = {{ batch.name }}
              />
            </div>
            <div class="mb-4">
              <label for="id_recipients" class="form-label">Recipients</label>
              <textarea id="autosize-demo" name="recipients" rows="3" class="form-control" placeholder="abc@gmail.com, xyz@gmail.com, admin@nepal.dev" style="   overflow: hidden;   overflow-wrap: break-word;   resize: none;   text-align: start;   height: 78.6px; " required>{% for recipient in batch.recipients_as_list %}{{ recipient }},{% endfor %}</textarea>
            </div>
            <button
            type="button"
            class="btn btn-secondary mt-3"
            data-bs-toggle="modal"
            data-bs-target="#cancelModal">
            Cancel
          </button>
            <button type="submit" class="btn btn-primary mt-3">Update</button>

            <!-- Cancel Modal -->
            <div
              class="modal fade"
              id="cancelModal"
              tabindex="-1"
              aria-labelledby="cancelModalLabel"
              aria-hidden="true"
            >
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="cancelModalLabel">Cancel</h5>
                    <button
                      type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"
                    ></button>
                  </div>
                  <div class="modal-body">Are you sure you want to cancel?</div>
                  <div class="modal-footer">
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-bs-dismiss="modal"
                    >
                      No
                    </button>
                    <a href="{% url 'batches' %}"  class="btn btn-primary">Yes</a>
                  </div>
                </div>
              </div>
            </div>
          </form>

          <script>
            textarea = document.querySelector("#autosize-demo")
            autoResizeTextarea(textarea) 
            htmx.process(htmx.find('#form2'))
          </script>
          

templates/components/toast.html
{% if messages %} {% for message in messages %}
  <div
    class="bs-toast toast toast-ex show animate__animated my-2 fade bg-{{message.tags}} animate__fade hide"
    role="alert"
    aria-live="assertive"
    aria-atomic="true"
    data-bs-delay="2000">
    <div class="toast-header">
      <i class="bx bx-bell me-2"></i>
      <div class="me-auto fw-medium">{{messages.tags}}</div>
      <small> right now</small>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="toast"
        aria-label="Close"
      ></button>
    </div>
    <div class="toast-body">{{message.message}}</div>
  </div>
  <span class="d-none"
  hx-get="{% url 'batch_list'  %}"
  hx-target="#batchesListCard"
  hx-swap="innerHTML"
  hx-indicator="true"
  hx-trigger="load"
  ></span>
  {% endfor %} {% endif %}

templates/components/view_mail.html
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">
      <small class="text-muted">{{ mailing.subject|upper }}</small>
    </h5>
  </div>
  <div class="modal-body">
    <div class="d-flex flex-column mb-3">
      <div class="d-flex justify-content-between align-items-center mb-2">
        <div>
          Batches:
          {% for batch in mailing.batches.all %}
            {{ batch.name }}{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </div>
        <div>
          {% if mailing.tracking %}
            <span class="badge bg-label-info rounded-pill">Tracking</span>
          {% endif %}
          <span class="badge bg-label-primary rounded-pill">{{ mailing.attachments.count }} Attachments</span>
          {% if mailing.sent %}
            <span class="badge bg-label-success rounded-pill">Sent</span>
          {% else %}
            <span class="badge bg-label-warning rounded-pill">Pending</span>
          {% endif %}
        </div>
      </div>
      <div class="mb-3">
        <div class="mb-3 border-bottom pb-3">
          {{ mailing.message|safe }}
        </div>
        <div>
          <h6 class="fw-semibold mb-2">Attachments:</h6>
          {% if not mailing.attachments.count %}
          No Attachments Found
          {% endif %}
          <ul class="list-unstyled">
            {% for attachment in mailing.get_attachments %}
              <li class="mb-1">
                <a href="{{ attachment.file.url }}" target="_blank"  class="text-primary text-decoration-none">{{ attachment.file.name }}</a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button 
    type="button" 
    class="btn btn-secondary" 
    onclick="closeModal()"
    >Close</button>
    <button type="button" class="btn btn-primary">Save changes</button>
  </div>

<script>
  function closeModal() {
    $('#myModal').removeClass('show').hide(); // Hide the modal
    $('.modal-backdrop').remove(); // Remove the modal backdrop
  }
</script>